import { readFile, writeFile } from "node:fs/promises";
import { resolve } from "node:path";

import { BRAND_SYSTEM } from "../src/brand/system";

const ROOT = resolve(process.cwd());
const CHECK_MODE = process.argv.includes("--check");
const LIVE_BASE_URL = "https://www.brand.raidguild.org";

function renderCssBlock(selector: string, tokens: Record<string, string>) {
  const declarations = Object.entries(tokens)
    .map(([name, value]) => `  ${name}: ${value};`)
    .join("\n");

  return `${selector} {\n${declarations}\n}`;
}

function generateTokenCss() {
  const blocks = [
    "/* This file is generated by scripts/generate-brand-artifacts.ts. */",
    "/* Edit src/brand/system.ts, then run npm run generate:brand. */",
    renderCssBlock(":root", BRAND_SYSTEM.baseTokens),
  ];

  for (const reign of BRAND_SYSTEM.reigns) {
    blocks.push(renderCssBlock(`[data-brand-reign="${reign.id}"]`, reign.tokens));

    if (reign.id === "tw") {
      blocks.push(
        renderCssBlock(`[data-brand-reign="tw"] body`, {
          "--font-display": '"RG Alchemion", Arial, sans-serif',
          "--font-body": '"RG Fratelli", Arial, sans-serif',
        }),
      );
    }
  }

  blocks.push(
    renderCssBlock(".dark", {
      "--background": "var(--moloch-800)",
      "--foreground": "var(--scroll-100)",
    }),
  );

  for (const reign of BRAND_SYSTEM.reigns) {
    if (reign.darkTokens) {
      blocks.push(
        renderCssBlock(`.dark[data-brand-reign="${reign.id}"]`, reign.darkTokens),
      );
    }
  }

  return `${blocks.join("\n\n")}\n`;
}

function generateRuntimeData() {
  const reigns = BRAND_SYSTEM.reigns.map((reign) => ({
      id: reign.id,
      steward: reign.steward,
      label: reign.label,
      status: reign.status,
      available: reign.available,
      summary: reign.summary,
      sourceLabel: reign.sourceLabel,
      contributionNote: reign.contributionNote,
      palette: reign.palette,
      sourceUrl: reign.sourceUrl ?? null,
      evidenceNote: reign.evidenceNote ?? null,
    }));
  const runtimeSystem = {
    ...BRAND_SYSTEM,
    reigns: BRAND_SYSTEM.reigns.map((reign) => ({
      ...reign,
      sourceUrl: reign.sourceUrl ?? null,
      evidenceNote: reign.evidenceNote ?? null,
      darkTokens: reign.darkTokens ?? null,
    })),
  };

  return `/* This file is generated by scripts/generate-brand-artifacts.ts. */\n` +
    `/* Edit src/brand/system.ts, then run npm run generate:brand. */\n\n` +
    `export const BRAND_SYSTEM = ${JSON.stringify(runtimeSystem, null, 2)} as const;\n\n` +
    `export const BRAND_REIGNS = ${JSON.stringify(reigns, null, 2)} as const;\n`;
}

function colorScale(prefix: "moloch" | "scroll" | "neutral") {
  const suffixes = prefix === "neutral"
    ? ["100", "200", "300", "400", "500", "600", "700", "800", "white", "black"]
    : ["100", "200", "300", "400", "500", "600", "700", "800"];

  return Object.fromEntries(
    suffixes.map((suffix) => [
      suffix,
      BRAND_SYSTEM.baseTokens[`--${prefix}-${suffix}`].toUpperCase(),
    ]),
  );
}

function generatePublicManifest() {
  const { illustrations } = BRAND_SYSTEM.assets;
  const sceneCount = Object.values(illustrations.scenesBySize)
    .reduce((total, collection) => total + collection.scenes.length, 0);
  const totalFiles = sceneCount * illustrations.palettes.length * Object.keys(illustrations.tones).length * 2;

  const manifest = {
    $schema: "https://raidguild.org/schemas/brand-manifest-v1.json",
    name: "RaidGuild Brand Assets Manifest",
    version: BRAND_SYSTEM.release.brandVersion,
    schemaVersion: BRAND_SYSTEM.release.schemaVersion,
    generatedAt: BRAND_SYSTEM.release.generatedAt,
    sourceRevision: BRAND_SYSTEM.release.sourceRevision,
    brandRefresh: "Louchi / Venture Beyond",
    description: "Machine-readable inventory of RaidGuild brand assets and its versioned steward-reign guidance.",
    sourceOfTruth: "https://github.com/raid-guild/brand",
    companionDocs: {
      assetManifestMarkdown: "https://github.com/raid-guild/brand/blob/main/BRAND-ASSETS.md",
      developerHandbook: "AGENTS.md",
      uiComponents: "docs/ui-components.md",
      tokensSource: "src/generated/brand-tokens.css",
    },
    baseUrls: {
      live: LIVE_BASE_URL,
      githubRaw: "https://raw.githubusercontent.com/raid-guild/brand/main/public",
      githubTree: "https://github.com/raid-guild/brand/tree/main/public",
    },
    downloadRule: "Any repo path under public/... is served at {live}/... with the public/ prefix removed.",
    namingConvention: {
      colorCodes: { m: "Moloch compatibility scale", s: "Scroll compatibility scale" },
      example: "m500 = Moloch 500; m800-s100 = Moloch 800 mark on a Scroll 100 background.",
    },
    guidelines: {
      identity: {
        durableElement: "Black crossed-swords logomark",
        masterAsset: `${LIVE_BASE_URL}${BRAND_SYSTEM.durableCore.canonicalBlackSvg}`,
        markId: BRAND_SYSTEM.durableCore.canonicalMarkId,
        markVersion: BRAND_SYSTEM.durableCore.markVersion,
        rules: [
          BRAND_SYSTEM.durableCore.recognitionRule,
          BRAND_SYSTEM.durableCore.alterationRule,
          ...BRAND_SYSTEM.durableCore.provenanceRequirements,
        ],
      },
      versioning: {
        default: BRAND_SYSTEM.defaultReign,
        storageKey: BRAND_SYSTEM.reignStorageKey,
        reigns: BRAND_SYSTEM.reigns.map((reign) => ({
          id: reign.id,
          steward: reign.steward,
          status: reign.status,
          available: reign.available,
          source: reign.sourceUrl ?? reign.sourceLabel,
          dataVersion: reign.dataVersion,
          ...(reign.appearances ? { appearances: reign.appearances } : {}),
          ...(reign.motion ? { motion: reign.motion } : {}),
          ...(reign.evidenceNote ? { evidence: reign.evidenceNote } : {}),
        })),
        practices: BRAND_SYSTEM.practices,
      },
      colors: {
        note: "Semantic tokens are remapped by data-brand-reign. Moloch and Scroll retain compatibility names while their values follow the selected reign.",
        louchi: BRAND_SYSTEM.reigns[0].palette.map(({ name, value, role }) => ({ name, hex: value.toUpperCase(), role })),
        primary: BRAND_SYSTEM.reigns[0].palette.map(({ name, value, role }) => ({
          name,
          hex: value.toUpperCase(),
          role,
        })),
        scales: {
          moloch: colorScale("moloch"),
          scroll: colorScale("scroll"),
          neutral: colorScale("neutral"),
        },
        semanticLight: BRAND_SYSTEM.reigns[0].tokens,
        semanticDark: BRAND_SYSTEM.reigns[0].darkTokens,
      },
      typography: {
        reigns: Object.fromEntries(
          BRAND_SYSTEM.reigns.map((reign) => [
            reign.id,
            [reign.typography.display, reign.typography.body, reign.typography.mono]
              .filter(Boolean)
              .join(", "),
          ]),
        ),
        families: BRAND_SYSTEM.typography.families.map((family) => ({
          name: family.name,
          cssVar: family.cssVariable,
          role: family.role,
        })),
        scale: BRAND_SYSTEM.typography.scale.map((token) => ({
          token: token.token,
          px: token.sizePx,
          lineHeight: `${token.lineHeight * 100}%`,
          letterSpacing: token.letterSpacing,
          class: token.className,
        })),
      },
      layout: {
        containerCustom: "max-width 1280px, responsive padding",
        gridCustom: "4 cols (mobile) -> 8 (tablet) -> 12 (desktop)",
        radiusBase: "0.625rem (with radius-sm/md/lg/xl derived)",
      },
    },
    components: BRAND_SYSTEM.components,
    assets: {
      logos: {
        format: "svg",
        folder: `${LIVE_BASE_URL}/assets/logos/`,
        items: BRAND_SYSTEM.assets.logos.map((logo) => ({
          ...logo,
          url: `${LIVE_BASE_URL}/assets/logos/${logo.file}`,
        })),
      },
      icons: {
        format: "svg",
        sets: {
          "8bit": {
            urlPattern: `${LIVE_BASE_URL}/assets/icon/8bit/{name}.svg`,
            items: Object.entries(BRAND_SYSTEM.assets.roleIcons).map(([name, role]) => ({ name, role })),
          },
          dd: {
            urlPattern: `${LIVE_BASE_URL}/assets/icon/dd/{name}.svg`,
            items: BRAND_SYSTEM.assets.serviceIcons,
          },
          magic: {
            urlPattern: `${LIVE_BASE_URL}/assets/icon/magic/{name}.svg`,
            items: BRAND_SYSTEM.assets.magicIcons,
          },
        },
      },
      illustrations: {
        format: "webp",
        folder: `${LIVE_BASE_URL}/assets/webp/`,
        totalFiles,
        reignReferences: illustrations.reignReferences,
        referenceCollections: illustrations.referenceCollections,
        urlTemplates: {
          full: `${LIVE_BASE_URL}/assets/webp/{palette}/{size}/{scene}-{tone}.webp`,
          thumbnail: `${LIVE_BASE_URL}/assets/webp/{palette}/thumbnails/{size}/{scene}-{tone}.webp`,
        },
        dimensions: {
          palette: illustrations.palettes,
          tone: illustrations.tones,
          variantsPerScene: illustrations.palettes.length * Object.keys(illustrations.tones).length * 2,
        },
        scenesBySize: Object.fromEntries(
          Object.entries(illustrations.scenesBySize).map(([size, collection]) => [
            size,
            { ...collection, count: collection.scenes.length },
          ]),
        ),
      },
      fonts: {
        folder: `${LIVE_BASE_URL}/fonts/`,
        items: BRAND_SYSTEM.assets.fonts.map((font) => ({
          ...font,
          url: `${LIVE_BASE_URL}/fonts/${font.file}`,
        })),
      },
      social: {
        format: "png",
        dimensions: "400x400",
        folder: `${LIVE_BASE_URL}/assets/social/`,
        items: BRAND_SYSTEM.assets.social.map((asset) => ({
          ...asset,
          url: `${LIVE_BASE_URL}/assets/social/${asset.file}`,
        })),
      },
      guidelinesPdf: {
        format: "pdf",
        ...BRAND_SYSTEM.assets.guidelinesPdf,
        url: `${LIVE_BASE_URL}/assets/${BRAND_SYSTEM.assets.guidelinesPdf.file}`,
        rawUrl: `https://raw.githubusercontent.com/raid-guild/brand/main/public/assets/${BRAND_SYSTEM.assets.guidelinesPdf.file}`,
      },
    },
  };

  return `${JSON.stringify(manifest, null, 2)}\n`;
}

function generateMarkdownReference() {
  const rows = BRAND_SYSTEM.reigns
    .map((reign) => `| ${reign.label} | ${reign.status} | ${reign.dataVersion} | ${reign.sourceLabel} |`)
    .join("\n");

  return `<!-- Generated by scripts/generate-brand-artifacts.ts. Do not edit directly. -->\n` +
    `# Generated Brand Reference\n\n` +
    `- Brand release: \`${BRAND_SYSTEM.release.brandVersion}\`\n` +
    `- Schema: \`${BRAND_SYSTEM.release.schemaVersion}\`\n` +
    `- Default reign: \`${BRAND_SYSTEM.defaultReign}\`\n` +
    `- Canonical mark: \`${BRAND_SYSTEM.durableCore.canonicalBlackSvg}\`\n\n` +
    `| Reign | Status | Data version | Source |\n` +
    `| --- | --- | --- | --- |\n${rows}\n\n` +
    `Practices are a separate registry and are not nested under reigns.\n`;
}

async function validateCriticalLocalAssets() {
  const paths = [
    ...BRAND_SYSTEM.assets.logos.map((asset) => `public/assets/logos/${asset.file}`),
    ...BRAND_SYSTEM.assets.fonts.map((asset) => `public/fonts/${asset.file}`),
    ...BRAND_SYSTEM.assets.social.map((asset) => `public/assets/social/${asset.file}`),
    `public/assets/${BRAND_SYSTEM.assets.guidelinesPdf.file}`,
  ];

  await Promise.all(
    paths.map(async (relativePath) => {
      try {
        await readFile(resolve(ROOT, relativePath));
      } catch {
        throw new Error(`Missing critical brand asset: ${relativePath}`);
      }
    }),
  );
}

async function main() {
  await validateCriticalLocalAssets();

  const outputs = new Map<string, string>([
    ["src/generated/brand-tokens.css", generateTokenCss()],
    ["src/generated/brand-data.ts", generateRuntimeData()],
    ["public/brand-assets.json", generatePublicManifest()],
    ["docs/generated/brand-reference.md", generateMarkdownReference()],
  ]);

  let stale = false;

  for (const [relativePath, content] of outputs) {
    const path = resolve(ROOT, relativePath);

    if (CHECK_MODE) {
      const current = await readFile(path, "utf8").catch(() => "");
      if (current !== content) {
        stale = true;
        console.error(`Stale generated artifact: ${relativePath}`);
      }
    } else {
      await writeFile(path, content);
      console.log(`Generated ${relativePath}`);
    }
  }

  if (stale) {
    console.error("Run `npm run generate:brand` and commit the resulting changes.");
    process.exitCode = 1;
  }
}

void main();
