const componentIds = [
  "accordion", "badge", "breadcrumb", "button", "calendar", "card",
  "carousel", "chart", "checkbox", "combobox", "command", "data-table",
  "date-picker", "dialog", "drawer", "dropdown-menu", "form", "hover-card",
  "input", "item", "kbd", "label", "menubar", "multiselect",
  "navigation-menu", "pagination", "popover", "progress", "radio-group",
  "scroll-area", "select", "sheet", "sidebar", "skeleton", "slider", "switch",
  "table", "tabs", "textarea", "toggle", "tooltip", "wizard",
] as const;

const experimentalComponents = new Set<string>([
  "calendar", "carousel", "chart", "combobox", "command", "data-table",
  "date-picker", "form", "multiselect", "sidebar", "wizard",
]);

const interactionComponents = new Set<string>([
  "calendar", "carousel", "combobox", "command", "data-table", "date-picker",
  "dialog", "drawer", "form", "multiselect", "navigation-menu", "sheet", "wizard",
]);

const defaultStoryIds: Partial<Record<(typeof componentIds)[number], string>> = {
  accordion: "data-display-accordion--default",
  badge: "primitives-badge--default",
  breadcrumb: "navigation-breadcrumb--default",
  button: "primitives-button--default",
  calendar: "experimental-calendar--default",
  card: "data-display-card--default",
  carousel: "experimental-carousel--default",
  chart: "experimental-chart--default",
  checkbox: "primitives-checkbox--default",
  combobox: "experimental-combobox--default",
  command: "experimental-command--default",
  "data-table": "experimental-data-table--default",
  "date-picker": "experimental-date-picker--default",
  dialog: "overlays-dialog--default",
  drawer: "overlays-drawer--default",
  "dropdown-menu": "navigation-dropdown-menu--default",
  form: "experimental-form--default",
  "hover-card": "overlays-hover-card--default",
  input: "primitives-input--default",
  item: "data-display-item--default",
  kbd: "primitives-keyboard-key--default",
  label: "primitives-label--default",
  menubar: "navigation-menubar--default",
  multiselect: "experimental-multiselect--default",
  "navigation-menu": "navigation-navigation-menu--default",
  pagination: "navigation-pagination--default",
  popover: "overlays-popover--default",
  progress: "primitives-progress--default",
  "radio-group": "primitives-radio-group--default",
  "scroll-area": "data-display-scroll-area--default",
  select: "primitives-select--default",
  sheet: "overlays-sheet--default",
  sidebar: "experimental-sidebar--default",
  skeleton: "primitives-skeleton--default",
  slider: "primitives-slider--default",
  switch: "primitives-switch--default",
  table: "data-display-table--default",
  tabs: "navigation-tabs--default",
  textarea: "primitives-textarea--default",
  toggle: "primitives-toggle--default",
  tooltip: "overlays-tooltip--default",
  wizard: "experimental-wizard--default",
};

export const COMPONENTS = componentIds.map((id) => ({
  id,
  sourcePath: `src/components/ui/${id}.tsx`,
  stability: experimentalComponents.has(id) ? "experimental" : "stable",
  dependencies: [],
  providers: [],
  storyIds: defaultStoryIds[id] ? [defaultStoryIds[id]] : [],
  accessibilityExpected: !experimentalComponents.has(id),
  interactionTestExpected: interactionComponents.has(id),
}));
