import { brandSystemSchema } from "./schema";
import { COMPONENTS } from "./components";
import { PRACTICES } from "./practices";
import { TYPOGRAPHY } from "./typography";

const suedePalette = {
  "--moloch-100": "#f1efee",
  "--moloch-200": "#efc5bb",
  "--moloch-300": "#e39b8b",
  "--moloch-400": "#d25c41",
  "--moloch-500": "#bd482d",
  "--moloch-600": "#8b3521",
  "--moloch-700": "#5c2316",
  "--moloch-800": "#29100a",
  "--scroll-100": "#f9f7e7",
  "--scroll-200": "#ece5ac",
  "--scroll-300": "#dccd6a",
  "--scroll-400": "#d2c141",
  "--scroll-500": "#b5a22c",
  "--scroll-600": "#837820",
  "--scroll-700": "#534a13",
  "--scroll-800": "#211e07",
  "--neutral-100": "#f1efee",
  "--neutral-200": "#d5cecd",
  "--neutral-300": "#b9aeac",
  "--neutral-400": "#9e8e8a",
  "--neutral-500": "#806f6b",
  "--neutral-600": "#645754",
  "--neutral-700": "#433937",
  "--neutral-800": "#221d1c",
  "--neutral-white": "#fafafa",
  "--neutral-black": "#0d0d0d",
};

const suedeSemantic = {
  "--background": "var(--scroll-100)",
  "--foreground": "var(--moloch-800)",
  "--card": "var(--scroll-100)",
  "--card-foreground": "var(--moloch-800)",
  "--popover": "var(--scroll-100)",
  "--popover-foreground": "var(--moloch-800)",
  "--primary": "var(--moloch-500)",
  "--primary-foreground": "var(--scroll-100)",
  "--secondary": "var(--neutral-100)",
  "--secondary-foreground": "var(--moloch-800)",
  "--muted": "var(--neutral-100)",
  "--muted-foreground": "var(--neutral-600)",
  "--accent": "var(--moloch-500)",
  "--accent-foreground": "var(--scroll-100)",
  "--destructive": "var(--moloch-300)",
  "--border": "var(--neutral-200)",
  "--input": "var(--neutral-200)",
  "--ring": "var(--moloch-500)",
  "--chart-1": "var(--moloch-500)",
  "--chart-2": "var(--moloch-600)",
  "--chart-3": "var(--scroll-500)",
  "--chart-4": "var(--scroll-600)",
  "--chart-5": "var(--neutral-500)",
  "--sidebar": "var(--scroll-100)",
  "--sidebar-foreground": "var(--moloch-800)",
  "--sidebar-primary": "var(--moloch-500)",
  "--sidebar-primary-foreground": "var(--scroll-100)",
  "--sidebar-accent": "var(--neutral-100)",
  "--sidebar-accent-foreground": "var(--moloch-800)",
  "--sidebar-border": "var(--neutral-200)",
  "--sidebar-ring": "var(--moloch-500)",
};


const logoDescriptions: Record<string, string> = {
  "symbol-black.svg": "Canonical black master mark",
  "full-m800.svg": "Full logo, Moloch 800 (floating)",
  "full-m500.svg": "Full logo, Moloch 500 (floating)",
  "full-s100.svg": "Full logo, Scroll 100 (floating, for dark backgrounds)",
  "full-m500-m800.svg": "Moloch 500 mark on Moloch 800 background",
  "full-m800-m500.svg": "Moloch 800 mark on Moloch 500 background",
  "full-m800-s100.svg": "Moloch 800 mark on Scroll 100 background",
  "full-s100-s700.svg": "Scroll 100 mark on Scroll 700 background",
  "symbol-m800.svg": "Symbol, Moloch 800 (floating)",
  "symbol-m500.svg": "Symbol, Moloch 500 (floating)",
  "symbol-s700.svg": "Symbol, Scroll 700 (floating)",
  "symbol-m500-m800.svg": "Moloch 500 symbol on Moloch 800 background",
  "symbol-m800-m500.svg": "Moloch 800 symbol on Moloch 500 background",
  "symbol-m800-s100.svg": "Moloch 800 symbol on Scroll 100 background",
  "symbol-s100-s700.svg": "Scroll 100 symbol on Scroll 700 background",
};

const logoFiles = Object.keys(logoDescriptions);

const brandSystemSource = {
  release: {
    schemaVersion: "1.0.0",
    brandVersion: "2026.8.0",
    generatedAt: "2026-08-18T00:00:00.000Z",
    sourceRevision: "feat/versioned-brand-reigns@221764d",
    compatibility: {
      minimumSchemaVersion: "1.0.0",
      deprecatedBefore: null,
    },
  },
  durableCore: {
    canonicalMarkId: "core.crossed-swords.black",
    markVersion: "1.0.0",
    canonicalBlackSvg: "/assets/logos/symbol-black.svg",
    recognitionRule: "The crossed-swords silhouette must remain recognizable.",
    alterationRule: "Document a geometry change as a new mark version.",
    provenanceRequirements: [
      "Use the crossed-swords mark or an approved variant.",
      "Provide a route back to RaidGuild.org.",
    ],
    relationshipPhrases: ["A RaidGuild practice", "Operating through RaidGuild LLC"],
  },
  defaultReign: "louchi",
  reignStorageKey: "raidguild-brand-reign",
  baseTokens: {
    "--radius": "0.625rem",
    ...suedePalette,
    ...suedeSemantic,
    "--reign-ink": "#29100a",
    "--reign-deep": "#29100a",
    "--reign-field": "#f9f7e7",
    "--reign-signal": "#bd482d",
    "--reign-highlight": "#534a13",
  },
  reigns: [
    {
      id: "louchi",
      steward: "Louchi",
      label: "Louchi — Latest",
      status: "latest",
      available: true,
      summary: "A Moebius-influenced system of deep teal, cyan, parchment, coral, and acid lime, built around expansive editorial type and speculative-world imagery.",
      direction: "Moebius-influenced speculative worlds, expansive editorial typography, spatial composition, and cinematic motion.",
      sourceLabel: "Venture Beyond redesign",
      sourceUrl: "https://github.com/raid-guild/website/tree/feat/venture-beyond-redesign",
      contributionNote: "Stewarded by Louchi and made real through the work, critique, and adoption of many Guild contributors.",
      palette: [
        { name: "Ink", value: "#102d2c", role: "Canonical dark ink" },
        { name: "Deep Teal", value: "#0a292b", role: "Immersive surface" },
        { name: "Cyan", value: "#b8e0df", role: "Open field" },
        { name: "Parchment", value: "#efe9d7", role: "Primary canvas" },
        { name: "Coral", value: "#ee3c78", role: "Signal and action" },
        { name: "Acid Lime", value: "#d7e34d", role: "Highlight and status" },
      ],
      tokens: {
        "--moloch-100": "#e7f4f3", "--moloch-200": "#b8e0df", "--moloch-300": "#78c5c3", "--moloch-400": "#ee709a",
        "--moloch-500": "#ee3c78", "--moloch-600": "#b84067", "--moloch-700": "#315654", "--moloch-800": "#0a292b",
        "--scroll-100": "#efe9d7", "--scroll-200": "#e5dfc8", "--scroll-300": "#d7e34d", "--scroll-400": "#c7d13f",
        "--scroll-500": "#9fa82f", "--scroll-600": "#667325", "--scroll-700": "#102d2c", "--scroll-800": "#071c1d",
        "--neutral-100": "#e7eeea", "--neutral-200": "#cbd9d3", "--neutral-300": "#a7bdb7", "--neutral-400": "#799590",
        "--neutral-500": "#58746f", "--neutral-600": "#3e5d59", "--neutral-700": "#274440", "--neutral-800": "#102d2c",
        "--neutral-white": "#fffdf5", "--neutral-black": "#060609",
        "--background": "var(--scroll-100)", "--foreground": "var(--scroll-700)", "--card": "#f5f0e2", "--card-foreground": "var(--scroll-700)",
        "--popover": "#f5f0e2", "--popover-foreground": "var(--scroll-700)", "--primary": "var(--moloch-500)", "--primary-foreground": "var(--scroll-100)",
        "--secondary": "var(--moloch-200)", "--secondary-foreground": "var(--scroll-700)", "--muted": "#e2e9df", "--muted-foreground": "#3e5d59",
        "--accent": "var(--scroll-300)", "--accent-foreground": "var(--scroll-700)", "--destructive": "#b84031", "--border": "#9db2ac", "--input": "#9db2ac", "--ring": "var(--moloch-500)",
        "--chart-1": "var(--moloch-500)", "--chart-2": "var(--moloch-300)", "--chart-3": "var(--scroll-300)", "--chart-4": "#b84031", "--chart-5": "var(--scroll-700)",
        "--sidebar": "var(--scroll-100)", "--sidebar-foreground": "var(--scroll-700)", "--sidebar-primary": "var(--moloch-500)", "--sidebar-primary-foreground": "var(--scroll-100)",
        "--sidebar-accent": "var(--moloch-200)", "--sidebar-accent-foreground": "var(--scroll-700)", "--sidebar-border": "#9db2ac", "--sidebar-ring": "var(--moloch-500)",
        "--reign-ink": "#102d2c", "--reign-deep": "#0a292b", "--reign-field": "#b8e0df", "--reign-signal": "#ee3c78", "--reign-highlight": "#d7e34d",
      },
      darkTokens: {
        "--background": "var(--moloch-800)", "--foreground": "var(--scroll-100)", "--card": "#102d2c", "--card-foreground": "var(--scroll-100)",
        "--popover": "#102d2c", "--popover-foreground": "var(--scroll-100)", "--muted": "#274440", "--muted-foreground": "#b8e0df", "--border": "#58746f", "--input": "#58746f",
      },
      typography: { display: "Mazius Display", body: "EB Garamond", mono: "Ubuntu Mono" },
      dataVersion: "1.0.0",
    },
    {
      id: "suede",
      steward: "Suede",
      label: "Suede",
      status: "archived",
      available: true,
      summary: "The warm Moloch and Scroll system: calligraphic editorial typography, D&D role language, and a red, parchment, and earthen-gold palette.",
      direction: "Warm Moloch and Scroll palettes, Mazius and EB Garamond typography, D&D role language, and technology-forward line art.",
      sourceLabel: "Brand repository",
      sourceUrl: "https://github.com/raid-guild/brand",
      contributionNote: "Stewarded by Suede with design, development, content, and system contributions from across the Guild.",
      palette: [
        { name: "Moloch 800", value: "#29100a", role: "Primary dark" },
        { name: "Moloch 500", value: "#bd482d", role: "Primary action" },
        { name: "Scroll 100", value: "#f9f7e7", role: "Primary canvas" },
        { name: "Scroll 700", value: "#534a13", role: "Warm accent" },
        { name: "Neutral Black", value: "#0d0d0d", role: "Canonical mark" },
      ],
      tokens: {
        "--reign-ink": "#29100a", "--reign-deep": "#29100a", "--reign-field": "#f9f7e7", "--reign-signal": "#bd482d", "--reign-highlight": "#534a13",
      },
      typography: { display: "Mazius Display", body: "EB Garamond", mono: "Ubuntu Mono" },
      dataVersion: "1.0.0",
    },
    {
      id: "tw",
      steward: "TW",
      label: "TW",
      status: "archived",
      available: true,
      summary: "A high-energy Webflow era using rust red, parchment, oversized custom type, tickers, and playful motion.",
      direction: "Oversized Alchemion and Fratelli typography, tickers, playful motion, rust red, and parchment.",
      sourceLabel: "Witch archive",
      sourceUrl: "https://www.raidguild.org/witch",
      contributionNote: "Stewarded by TW as a collective production involving many contributors across identity, illustration, motion, copy, and implementation.",
      palette: [
        { name: "Primary", value: "#a8452c", role: "Primary field" },
        { name: "Black", value: "#29100a", role: "Type and mark" },
        { name: "Secondary", value: "#f9f7e7", role: "Canvas and contrast" },
      ],
      tokens: {
        "--moloch-100": "#f4ded7", "--moloch-200": "#e6b7a9", "--moloch-300": "#d78d76", "--moloch-400": "#c76548",
        "--moloch-500": "#a8452c", "--moloch-600": "#813420", "--moloch-700": "#542116", "--moloch-800": "#29100a",
        "--scroll-100": "#f9f7e7", "--scroll-200": "#eee9c8", "--scroll-300": "#e0d889", "--scroll-400": "#c8bc55",
        "--scroll-500": "#a89b37", "--scroll-600": "#7a6f26", "--scroll-700": "#534a13", "--scroll-800": "#211e07",
        "--background": "var(--moloch-500)", "--foreground": "var(--moloch-800)", "--card": "var(--scroll-100)", "--card-foreground": "var(--moloch-800)",
        "--popover": "var(--scroll-100)", "--popover-foreground": "var(--moloch-800)", "--primary": "var(--moloch-800)", "--primary-foreground": "var(--scroll-100)",
        "--secondary": "var(--scroll-100)", "--secondary-foreground": "var(--moloch-800)", "--muted": "#c9654d", "--muted-foreground": "var(--moloch-800)",
        "--accent": "var(--scroll-100)", "--accent-foreground": "var(--moloch-800)", "--destructive": "#742618", "--border": "#29100a4d", "--input": "#29100a4d", "--ring": "var(--scroll-100)",
        "--reign-ink": "#29100a", "--reign-deep": "#29100a", "--reign-field": "#f9f7e7", "--reign-signal": "#a8452c", "--reign-highlight": "#f9f7e7",
      },
      darkTokens: {
        "--background": "var(--moloch-800)", "--foreground": "var(--scroll-100)", "--muted": "var(--moloch-700)",
        "--muted-foreground": "var(--scroll-200)", "--border": "#f9f7e74d", "--input": "#f9f7e74d",
      },
      typography: { display: "RG Alchemion", body: "RG Fratelli" },
      dataVersion: "1.0.0",
    },
    {
      id: "ven",
      steward: "Ven",
      label: "Ven",
      status: "reconstructed",
      available: true,
      summary: "A high-contrast early design-system era built from black fields, electric pink, white, graphite, violet, and signal yellow.",
      direction: "High-contrast design-system language using black fields, electric pink line work, ornate display typography, monospaced technical annotation, fantasy role icons, and violet-to-pink framing.",
      sourceLabel: "Surviving RG UI sheets and illustration",
      contributionNote: "The surviving one-sheet explicitly credits multiple contributors across brand stewardship, design systems, icons, and implementation.",
      evidenceNote: "Partially reconstructed from a surviving overview, colour sheet, and neon sword-and-skull illustration.",
      palette: [
        { name: "Black", value: "#000000", role: "Primary field" },
        { name: "Raid Pink", value: "#ff3864", role: "Primary signal" },
        { name: "White", value: "#ffffff", role: "High-contrast type and canvas" },
        { name: "Graphite", value: "#2b2c34", role: "Secondary surface" },
        { name: "Violet", value: "#b66ad6", role: "Secondary accent" },
        { name: "Signal Yellow", value: "#fcfb75", role: "Secondary highlight" },
      ],
      tokens: {
        "--moloch-100": "#ffe5eb", "--moloch-200": "#ffbdcc", "--moloch-300": "#ff85a0", "--moloch-400": "#ff5d82",
        "--moloch-500": "#ff3864", "--moloch-600": "#d9244e", "--moloch-700": "#8f1735", "--moloch-800": "#000000",
        "--scroll-100": "#ffffff", "--scroll-200": "#f1f1f2", "--scroll-300": "#fcfb75", "--scroll-400": "#e9e85f",
        "--scroll-500": "#b6b63e", "--scroll-600": "#77772b", "--scroll-700": "#2b2c34", "--scroll-800": "#000000",
        "--neutral-100": "#ffffff", "--neutral-200": "#dedee2", "--neutral-300": "#b6b6be", "--neutral-400": "#878893",
        "--neutral-500": "#686974", "--neutral-600": "#4b4c56", "--neutral-700": "#2b2c34", "--neutral-800": "#000000", "--neutral-white": "#ffffff", "--neutral-black": "#000000",
        "--background": "#000000", "--foreground": "#ffffff", "--card": "#2b2c34", "--card-foreground": "#ffffff", "--popover": "#2b2c34", "--popover-foreground": "#ffffff",
        "--primary": "#ff3864", "--primary-foreground": "#000000", "--secondary": "#b66ad6", "--secondary-foreground": "#000000", "--muted": "#2b2c34", "--muted-foreground": "#dedee2",
        "--accent": "#fcfb75", "--accent-foreground": "#000000", "--destructive": "#d9244e", "--border": "#686974", "--input": "#686974", "--ring": "#ff3864",
        "--reign-ink": "#ff3864", "--reign-deep": "#000000", "--reign-field": "#ffffff", "--reign-signal": "#ff3864", "--reign-highlight": "#fcfb75",
      },
      darkTokens: {
        "--background": "#000000", "--foreground": "#ffffff", "--card": "#2b2c34", "--card-foreground": "#ffffff", "--popover": "#2b2c34", "--popover-foreground": "#ffffff",
        "--primary-foreground": "#000000", "--muted": "#2b2c34", "--muted-foreground": "#dedee2", "--border": "#686974", "--input": "#686974",
      },
      typography: { display: "Mazius Display", body: "EB Garamond", mono: "Ubuntu Mono" },
      dataVersion: "0.1.0-reconstructed",
    },
  ],
  practices: PRACTICES,
  typography: TYPOGRAPHY,
  components: COMPONENTS,
  assets: {
    logos: logoFiles.map((file) => ({
      id: file === "symbol-black.svg" ? "core.crossed-swords.black" : `suede.${file.replace(".svg", "")}`,
      file,
      type: file.startsWith("symbol-") ? "logomark" : "logotype",
      description: logoDescriptions[file],
      ownership: file === "symbol-black.svg" ? "durable-core" : "suede",
    })),
    roleIcons: {
      alchemist: "DAO Consultant", archer: "Visual Design", cleric: "Account Manager", druid: "Data Science", dwarf: "Treasury",
      healer: "Internal Operations", hunter: "Business Development", monk: "Project Management", necromancer: "DevOps", paladin: "Backend Development",
      ranger: "UX Design", rogue: "Legal", scribe: "Content Creation", sorcerer: "Role character", tavernkeeper: "Community",
      warrior: "Frontend Development", wizard: "Smart Contracts",
    },
    serviceIcons: ["community", "consultation", "culture", "dao", "education", "experiment", "frontend", "fullstack", "learning", "manifesto", "marketing", "robot", "spear", "sprint", "swords"],
    magicIcons: ["candle", "cauldron", "chalice", "crystal", "feather", "flask", "hourglass", "lantern", "moon", "pumpkin", "sparkle", "star", "stars"],
    fonts: [
      { file: "MAZIUSREVIEW20.09-Regular.otf", family: "Mazius Display", weight: "Regular" },
      { file: "MAZIUSREVIEW20.09-Regular.woff", family: "Mazius Display", weight: "Regular (woff)" },
      { file: "MaziusDisplay-Bold.otf", family: "Mazius Display", weight: "Bold" },
      { file: "MaziusDisplay-Extraitalic.otf", family: "Mazius Display", weight: "Extra Italic" },
      { file: "MaziusDisplay-ExtraItalicBold.otf", family: "Mazius Display", weight: "Extra Italic Bold" },
      { file: "EBGaramond-VariableFont_wght.ttf", family: "EB Garamond", weight: "Variable" },
      { file: "EBGaramond-Italic-VariableFont_wght.ttf", family: "EB Garamond", weight: "Italic Variable" },
    ],
    social: [
      { file: "400x400_dark.png", description: "Dark background avatar" },
      { file: "400x400_light.png", description: "Light background avatar" },
      { file: "400x400_red.png", description: "Red (Moloch) avatar" },
    ],
    guidelinesPdf: {
      file: "RaidGuild_brand_guidelines.pdf",
      description: "Complete human-facing brand guidelines (2024 Q4 Refresh).",
    },
    illustrations: {
      palettes: ["moloch500", "moloch800", "scroll100", "scroll700"],
      tones: { c: "full color", bw: "black and white" },
      scenesBySize: {
        "1440x1440": { aspect: "square", scenes: ["castle-flag", "castle-staff", "desk-work", "forge-anvil", "forge-building", "forge-duo", "forge-fire", "forge-work", "portal-arch", "ravens-flight", "stairs-spiral", "stone-monuments", "table-castle", "tree-mech", "trio-arch", "trio-backs", "trio-beast", "trio-mountain", "trio-orb", "trio-portal", "trio-portraits", "trio-profiles", "trio-warriors", "trio-weapons", "trio-wings", "warrior-solo", "warriors-armed", "warriors-belts", "warriors-casual", "warriors-confident", "warriors-forward", "warriors-magic", "warriors-masked", "warriors-moloch", "warriors-orbs", "warriors-ready", "warriors-standing", "warriors-triangle", "warriors-white"] },
        "1080x1440": { aspect: "portrait", scenes: ["arch-gate", "book-orb", "compass-circular", "raven-solo", "stairs-cloud", "stairs-curve", "stairs-twist", "stone-pedestal", "tower-floating", "tower-platform", "tower-tree", "tree-island"] },
        "1440x550": { aspect: "landscape", scenes: ["ship-front", "ship-mech"] },
      },
      reignReferences: {
        louchi: "https://github.com/raid-guild/website/tree/6e5f3ec8eade94ddb05a0eb63146aef4a7d80c65/public/images/neo",
        tw: "https://www.raidguild.org/witch/images/",
        suede: "https://www.brand.raidguild.org/assets/webp/",
        ven: "/images/reigns/ven/skull-sword.png",
      },
      referenceCollections: {
        louchi: {
          direction: "Expansive speculative landscapes place RaidGuild builders inside unfamiliar, optimistic worlds, pairing atmospheric detail with coral structures and cyan horizons.",
          hero: {
            title: "RaidGuild Panorama",
            src: "https://raw.githubusercontent.com/raid-guild/website/6e5f3ec8eade94ddb05a0eb63146aef4a7d80c65/public/images/neo/raidguild-panorama.png",
            alt: "A panoramic view of the Louchi-era RaidGuild world",
            aspect: "aspect-[3824/1632]",
          },
          items: [
            { title: "Character Style Guide", src: "/images/reigns/louchi/character-style-guide.png", alt: "Louchi-era character art-direction sheet showing three RaidGuild explorers and guidance for their clean, flat, Moebius-influenced visual language", aspect: "aspect-[1746/2484]", kind: "art-direction" },
            { title: "Sky Citadel", src: "https://raw.githubusercontent.com/raid-guild/website/6e5f3ec8eade94ddb05a0eb63146aef4a7d80c65/public/images/neo/sky-citadel.png", alt: "A cloaked traveler overlooking a floating coral citadel", aspect: "aspect-[972/1619]" },
            { title: "Protocol Garden", src: "https://raw.githubusercontent.com/raid-guild/website/6e5f3ec8eade94ddb05a0eb63146aef4a7d80c65/public/images/neo/field-protocol-garden.png", alt: "A cartographer studying a luminous network city", aspect: "aspect-[971/1619]" },
            { title: "Signal Commons", src: "https://raw.githubusercontent.com/raid-guild/website/6e5f3ec8eade94ddb05a0eb63146aef4a7d80c65/public/images/neo/field-signal-commons.png", alt: "A floating civic commons above the clouds", aspect: "aspect-[1122/1402]" },
            { title: "Autonomous Treasury", src: "https://raw.githubusercontent.com/raid-guild/website/6e5f3ec8eade94ddb05a0eb63146aef4a7d80c65/public/images/neo/field-autonomous-treasury.png", alt: "Engineers inspecting a monumental autonomous treasury", aspect: "aspect-[1003/1568]" },
          ],
        },
        tw: {
          direction: "Surreal witchcraft scenes, dense graphic symbols, high-energy crops, rust, parchment, oversized type, and playful motion.",
          items: [
            { title: "Witchcraft 08", src: "https://www.raidguild.org/witch/images/witchcraft-08_0-15-1.png", alt: "TW-era RaidGuild witchcraft illustration", aspect: "aspect-[2544/2944]" },
            { title: "Witchcraft 05", src: "https://www.raidguild.org/witch/images/witchcraft-05_0-20.png", alt: "TW-era surreal fantasy landscape", aspect: "aspect-[6667/5417]" },
            { title: "Witchcraft 04", src: "https://www.raidguild.org/witch/images/witchcraft-04_0-2.png", alt: "TW-era graphic fantasy scene", aspect: "aspect-[6667/5417]" },
          ],
        },
      },
    },
  },
};

export const BRAND_SYSTEM = brandSystemSchema.parse(brandSystemSource);
